name: Setup

runs:
  using: composite
  steps:      
    - name: Setup Node
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20

    - name: Setup Cache
      uses: actions/cache@v4.0.2
      id: cache
      with:
        path: '**/node_modules'
        key: npm-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
